#pragma once
//ÉwÉbÉ_Å[ÇÕÇ±Ç±Ç…Ç‹Ç∆ÇﬂÇÈbyÇÕÇ‚Çµ
#include"Maptip/Fuda.h"
#include"Base/Base.h"
#include"Maptip/Map.h"
#include"Enemy/Enemy.h"
#include"Player/kamano.h"
#include "UI/AnimData.h"
#include"Enemy/EnemyManager.h"
#include"UI/Gameover.h"
#include "Enemy/Enemy.h"
#include "UI/Goal.h"
#include "UI/Title.h"
#include "Game/Text.h"
#include"Maptip/fmfmap.h"
#include"Maptip/AreaChange.h"
#include"UI/Canvas.h"
#include"UI/Gauge.h"
#include"Game/Game.h"
#include"UI/Save.h"
#include"Enemy/Dijkstra.h"
#include"UI/Gameclear.h"
#include"UI/MyUtility.h"
#include"Maptip/aya.h"
#include"Maptip/K.h"
#include"UI/FudaUI.h"
